### ISSUE TITLE
Model in folder 'configs' with filename 'sd_xl_base.yaml' not found.

### ISSUE THREAD

**Issue by slmonker** [zmwv823/ComfyUI_Anytext#1]
这个inpaint的sdxl inpaint base 是不是不对劲啊？节点调用找不到这个文件名，改名会有其他报错

**Comment by zmwv823** [comment]
我的，记错了comfy官方只内置了sd1.5和sd2.1的配置文件。
sdxl配置文件需要自己下载，基座模型和重绘模型参数有一处区别，不能通用。
ReadME已经更新，按照说明下一份就行。

**Comment by slmonker** [comment]
> 我的，记错了comfy官方只内置了sd1.5和sd2.1的配置文件。 sdxl配置文件需要自己下载，基座模型和重绘模型参数有一处区别，不能通用。 ReadME已经更新，按照说明下一份就行。

哈哈哈。感谢感谢，果然还得是咱同胞效率高！
