### ISSUE TITLE
节点怎么安装？

### ISSUE THREAD

**Issue by FanXiangTM** [zmwv823/ComfyUI_Anytext#2]

**Comment by zmwv823** [comment]
### 在`ComfyUI\custom_nodes`目录下`git clone https://github.com/zmwv823/ComfyUI_Anytext`
### 或者
![image](https://github.com/user-attachments/assets/c81464ab-20eb-4f09-ae36-0bc11862e47d)
### 然后解压到`ComfyUI\custom_nodes`
