### ISSUE TITLE
模型加载器是不是修改名字的时候给，删除了？

### ISSUE THREAD

**Issue by 748226917** [zmwv823/ComfyUI_Anytext#3]
模型加载器是不是修改名字的时候给，删除了？没有模型加载器节点了

**Comment by zmwv823** [comment]
没删，应该是clip文件夹或者text_encoders(comfyui最近突然将clip改成这个)中的某个文件夹不存在，导致索引失效，这样节点就加载失败。
如果都有，就需要看日志。
![image](https://github.com/user-attachments/assets/6bbfe0ff-21ec-4eea-a8db-79646d358568)

**Comment by 748226917** [comment]
了解了，已经可以用了。
