### ISSUE TITLE
字体保存的文件的路径是什么？

### ISSUE THREAD

**Issue by yuan-ying555** [zmwv823/ComfyUI_Anytext#4]

**Comment by zmwv823** [comment]
`ComfyUI\models\fonts`

**Comment by yuan-ying555** [comment]
![1733844976117](https://github.com/user-attachments/assets/be30ae45-3790-4ddc-9b51-db006d38e317)
![1733845070654](https://github.com/user-attachments/assets/3da9e7de-60ce-41d2-8557-a115227b9557)
请问这两个字体都是存在ComfyUI\models\fonts文件中么，手动下载的字体上传后，无法选择字体，只能auto_download

**Comment by yuan-ying555** [comment]
可不可以做个安装视频，特别是手动安装（上传模型/字体之类的，到那个文件夹内？）之前的一版在liblib有博主教怎么安装和使用，等看到了，这里换新版本了。。。与之前变化好大，不会安装。

**Comment by zmwv823** [comment]
> 可不可以做个安装视频，特别是手动安装（上传模型/字体之类的，到那个文件夹内？）之前的一版在liblib有博主教怎么安装和使用，等看到了，这里换新版本了。。。与之前变化好大，不会安装。

变化不大的，主要是优化了一些逻辑，少了很多bug，文件位置跟以前一样的，下面是老版的说明。
字体放进去之后，刷新UI才可以选择。如果还不行，可能是环境问题，到时候我再改一下索引方法。
https://github.com/zmwv823/ComfyUI_Anytext/blob/master/Image_Generation_AnyText/assets/README-Zh-CN.md

**Comment by yuan-ying555** [comment]
![1733886629424](https://github.com/user-attachments/assets/c8491ec4-8a78-4e69-9c95-dfd7b1e59cc7)
感谢您的解答，我这个用的是云端操作的，这个会有影响么？字体放入后重启了几次，还是无法选择。

**Comment by zmwv823** [comment]
改了一下索引方法，win本地测试没问题，云端没测试。
